services:
  phpadmin:
    image: phpmyadmin:5.2.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
    ports:
      - 8080:80

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    external: true
    name: ${VOLUME_MARIADB_DATA:-mariadb_data}
